@extends('layouts.admin.app')

@section('title', 'PHP Info')

@section('content')

    <section class="mb-6">
        <div class="flex flex-wrap items-center justify-between gap-4">
            <div>
                <h1 class="text-2xl font-bold tracking-tight text-slate-900">PHP Info</h1>
                <p class="mt-1 text-sm text-slate-500">Server PHP configuration and environment details</p>
            </div>
            <div class="flex items-center gap-3">
                <ol class="flex items-center gap-1 text-sm text-slate-400">
                    <li><a href="{{ routeHelper('dashboard') }}" class="transition-colors hover:text-primary">Home</a></li>
                    <li><i class="fas fa-chevron-right text-[9px]"></i></li>
                    <li class="font-medium text-slate-600">PHP Info</li>
                </ol>
            </div>
        </div>
    </section>

    <section class="mb-6">
        <div class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">
            <div class="flex items-center gap-3 border-b border-slate-200 px-5 py-4">
                <div class="grid h-9 w-9 place-items-center rounded-lg bg-primary/10 text-primary">
                    <i class="fas fa-info-circle"></i>
                </div>
                <div>
                    <h2 class="text-base font-semibold text-slate-900">PHP Environment</h2>
                    <p class="text-xs text-slate-500">Output generated by phpinfo()</p>
                </div>
            </div>
            <div class="overflow-x-auto p-5">
                @php
                    phpinfo();
                @endphp
            </div>
        </div>
    </section>

@endsection
